import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
const p = await ctx.newPage();
const B = 'http://127.0.0.1:3214';
p.on('response', r => { if (r.status() >= 500) console.log('HTTP', r.status(), r.url().slice(0,80)); });
await p.goto(B + '/profil', { waitUntil: 'networkidle' });
await p.waitForTimeout(800);
await p.getByText('Miguel', { exact: false }).first().click();
await p.waitForTimeout(1200);
await p.goto(B + '/technique/facture/e11df40c-f901-4232-9401-64701f8db9be', { waitUntil: 'networkidle' }).catch(e => console.log('goto:', e.message.slice(0,60)));
await p.waitForTimeout(1500);
const t = await p.locator('body').innerText();
console.log('page:', t.slice(0, 120).replace(/\n/g,' | '));
await b.close();
