-- =============================================================================
-- Catalogue d'anomalies — généré depuis l'export de « TEST Tech 3 »
--   795 lignes  ->  268 libellés distincts
--
-- Ne pas modifier à la main : régénérer avec
--   python3 outils/generer_catalogue.py <export.xlsx> > supabase/seed/02_catalogue_anomalies.sql
--
-- La gouvernante déclare en cherchant ici par mots-clés ; elle ne peut pas
-- saisir de texte libre. Ajouter une entrée est réservé à l'admin (voir RLS).
-- `occurrences` sert à trier les plus courantes en tête de liste.
-- =============================================================================

with source (libelle, mots_cles, type_code, occurrences) as (values
  ('Demande de vérification s''il y a la présence de punaises', array['demande', 'verification', 'presence', 'punaises']::text[], 'TECHNIQUE', 75),
  ('Nettoyage des filtres prévu dans le contrat avec Avir', array['nettoyage', 'filtres', 'prevu', 'contrat', 'avir']::text[], 'TECHNIQUE', 40),
  ('Changement des circuits électriques pour que la TV ne s''éteigne plus quand la carte est retirée', array['changement', 'circuits', 'electriques', 'eteigne', 'quand', 'carte', 'retiree']::text[], 'ELECTRIQUE', 37),
  ('lavabo bouché', array['lavabo', 'bouche']::text[], 'TECHNIQUE', 26),
  ('serrer le bras liseuse côté droit', array['serrer', 'bras', 'liseuse', 'cote', 'droit']::text[], 'TECHNIQUE', 16),
  ('remplacer l''économiseur d''énergie pour éclairage principal', array['remplacer', 'economiseur', 'energie', 'eclairage', 'principal']::text[], 'ELECTRIQUE', 15),
  ('lit côté gauche cassé', array['lit', 'cote', 'gauche', 'casse']::text[], 'TECHNIQUE', 14),
  ('flexible douche à changer', array['flexible', 'douche', 'changer']::text[], 'TECHNIQUE', 13),
  ('Spot à changer', array['spot', 'changer']::text[], 'ELECTRIQUE', 13),
  ('serrer le bras liseuse côté gauche', array['serrer', 'bras', 'liseuse', 'cote', 'gauche']::text[], 'TECHNIQUE', 12),
  ('Miroir plateau à changé', array['miroir', 'plateau', 'change']::text[], 'TECHNIQUE', 11),
  ('Changement des rideaux', array['changement', 'rideaux']::text[], 'TECHNIQUE', 10),
  ('Voir ce qu''il est possible de faire pour l’espace entre le mitigeur et le mur', array['voir', 'possible', 'espace', 'entre', 'mitigeur', 'mur']::text[], 'TECHNIQUE', 10),
  ('bloc secour/batterie a changer', array['bloc', 'secour', 'batterie', 'changer']::text[], 'TECHNIQUE', 9),
  ('Détection de punaises de lit au niveau de la tête de lit constaté le 11/10/24 par la societe Ecoflair', array['detection', 'punaises', 'lit', 'niveau', 'tete', 'constate', 'societe', 'ecoflair']::text[], 'TECHNIQUE', 8),
  ('joint sillicone dans le bac à douche', array['joint', 'sillicone', 'bac', 'douche']::text[], 'TECHNIQUE', 8),
  ('Lit côté droit cassé', array['lit', 'cote', 'droit', 'casse']::text[], 'TECHNIQUE', 8),
  ('bouton mitigeur douche manquant', array['bouton', 'mitigeur', 'douche', 'manquant']::text[], 'TECHNIQUE', 7),
  ('flexible fuit au niveau du pommeau de douche', array['flexible', 'fuit', 'niveau', 'pommeau', 'douche']::text[], 'TECHNIQUE', 7),
  ('refixer la liseuse de droite', array['refixer', 'liseuse', 'droite']::text[], 'TECHNIQUE', 7),
  ('Refixer la liseuse de gauche', array['refixer', 'liseuse', 'gauche']::text[], 'TECHNIQUE', 7),
  ('Refixer le miroir grossissant', array['refixer', 'miroir', 'grossissant']::text[], 'TECHNIQUE', 7),
  ('Changement du séche cheveux', array['changement', 'seche', 'cheveux']::text[], 'TECHNIQUE', 6),
  ('lampe bureau à réparer', array['lampe', 'bureau', 'reparer']::text[], 'TECHNIQUE', 6),
  ('Mettre une vis pour l''aimant de la porte dorée armoire (haut)', array['mettre', 'vis', 'aimant', 'porte', 'doree', 'armoire', 'haut']::text[], 'TECHNIQUE', 6),
  ('Télérupteur à changer (repris de l''ancien tableau technique )', array['telerupteur', 'changer', 'repris', 'ancien', 'tableau', 'technique']::text[], 'ELECTRIQUE', 6),
  ('urgent - joints sillicone douche - lavabo et wc à refaire complètement', array['urgent', 'joints', 'sillicone', 'douche', 'lavabo', 'refaire', 'completement']::text[], 'TECHNIQUE', 6),
  ('Vérifier que tous les joints de la douche et de la salle de bain ne présentent aucun defaut', array['verifier', 'tous', 'joints', 'douche', 'salle', 'bain', 'presentent', 'aucun']::text[], 'TECHNIQUE', 6),
  ('Ascenseur en panne - Il faut contacter KONE', array['ascenseur', 'panne', 'faut', 'contacter', 'kone']::text[], 'TECHNIQUE', 5),
  ('barriere de douche à fixer', array['barriere', 'douche', 'fixer']::text[], 'TECHNIQUE', 5),
  ('flexible douche qui fuit', array['flexible', 'douche', 'fuit']::text[], 'TECHNIQUE', 5),
  ('Télérupteur à changer - appliques murales sautent', array['telerupteur', 'changer', 'appliques', 'murales', 'sautent']::text[], 'ELECTRIQUE', 5),
  ('Verification contractuelle pour vérifier si''il n''y a pas de présence de rongeurs', array['verification', 'contractuelle', 'verifier', 'presence', 'rongeurs']::text[], 'TECHNIQUE', 5),
  ('changer connecteur lumiéres miroir SDB', array['changer', 'connecteur', 'lumieres', 'miroir', 'sdb']::text[], 'ELECTRIQUE', 4),
  ('deboucher l''evier', array['deboucher', 'evier']::text[], 'PLOMBERIE', 4),
  ('flexible de douche à changer', array['flexible', 'douche', 'changer']::text[], 'TECHNIQUE', 4),
  ('flexible liseuse côté droit à changer', array['flexible', 'liseuse', 'cote', 'droit', 'changer']::text[], 'TECHNIQUE', 4),
  ('L''eau coule dans la cuvette des WC', array['eau', 'coule', 'cuvette']::text[], 'TECHNIQUE', 4),
  ('Support gel douche à changer', array['support', 'gel', 'douche', 'changer']::text[], 'TECHNIQUE', 4),
  ('Télérupteur à changer - spot et leds', array['telerupteur', 'changer', 'spot', 'leds']::text[], 'ELECTRIQUE', 4),
  ('urgent - joints sillicone douche', array['urgent', 'joints', 'sillicone', 'douche']::text[], 'TECHNIQUE', 4),
  ('URGENT - Joints sillicone douche et lavabo à refaire complètement', array['urgent', 'joints', 'sillicone', 'douche', 'lavabo', 'refaire', 'completement']::text[], 'TECHNIQUE', 4),
  ('Vérifier s''il ne faut pas changer entièrement la colonne de douche', array['verifier', 'faut', 'changer', 'entierement', 'colonne', 'douche']::text[], 'TECHNIQUE', 4),
  ('Bouton pour le mitigeur douche à acheter car il n''y en a plus', array['bouton', 'mitigeur', 'douche', 'acheter', 'car']::text[], 'ACHATS', 3),
  ('Changement des rideaux - salle de bain', array['changement', 'rideaux', 'salle', 'bain']::text[], 'TECHNIQUE', 3),
  ('Changement flexible liseuse droite', array['changement', 'flexible', 'liseuse', 'droite']::text[], 'TECHNIQUE', 3),
  ('flexible liseuse côté gauche à changer', array['flexible', 'liseuse', 'cote', 'gauche', 'changer']::text[], 'TECHNIQUE', 3),
  ('Fuite depuis joint d’évacuation en dessous d’évier', array['fuite', 'depuis', 'joint', 'evacuation', 'dessous', 'evier']::text[], 'TECHNIQUE', 3),
  ('Il faut changer la bouilloire', array['faut', 'changer', 'bouilloire']::text[], 'TECHNIQUE', 3),
  ('Il manque des crochets pour faire tenir le rideau', array['manque', 'crochets', 'tenir', 'rideau']::text[], 'TECHNIQUE', 3),
  ('joint étanchéité pare douche', array['joint', 'etancheite', 'pare', 'douche']::text[], 'TECHNIQUE', 3),
  ('Joint pare douche', array['joint', 'pare', 'douche']::text[], 'TECHNIQUE', 3),
  ('Joint pour faire tenir le pommeau de douche', array['joint', 'tenir', 'pommeau', 'douche']::text[], 'TECHNIQUE', 3),
  ('La poignée de la fenêtre s''enlève', array['poignee', 'fenetre', 'enleve']::text[], 'TECHNIQUE', 3),
  ('Lavabo qui coule', array['lavabo', 'coule']::text[], 'TECHNIQUE', 3),
  ('Mettre une vis pour l''aimant de la porte dorée armoire (bas)', array['mettre', 'vis', 'aimant', 'porte', 'doree', 'armoire', 'bas']::text[], 'TECHNIQUE', 3),
  ('Moisissure présente sans la salle de bain', array['moisissure', 'presente', 'sans', 'salle', 'bain']::text[], 'TECHNIQUE', 3),
  ('porte d''entrée qui ne se verouille pas - urgent', array['porte', 'entree', 'verouille', 'urgent']::text[], 'ELECTRIQUE', 3),
  ('prise arrachée du mur sdb', array['prise', 'arrachee', 'mur', 'sdb']::text[], 'ELECTRIQUE', 3),
  ('remplacement bras de liseuse (coté gauche)', array['remplacement', 'bras', 'liseuse', 'cote', 'gauche']::text[], 'ELECTRIQUE', 3),
  ('Spot à coté de l''ascenseur à changer', array['spot', 'cote', 'ascenseur', 'changer']::text[], 'TECHNIQUE', 3),
  ('télécommande clim à remplacer', array['telecommande', 'clim', 'remplacer']::text[], 'TECHNIQUE', 3),
  ('voir avec miroitier pour miroir placard cassé en bas (grand)', array['voir', 'miroitier', 'miroir', 'placard', 'casse', 'bas', 'grand']::text[], 'TECHNIQUE', 3),
  ('Bac de douche à changer', array['bac', 'douche', 'changer']::text[], 'TECHNIQUE', 2),
  ('Bac de douche à changer - URGENT', array['bac', 'douche', 'changer', 'urgent']::text[], 'TECHNIQUE', 2),
  ('batterie du bloc secours changé (celui au dessus de la porte d''entrée)', array['batterie', 'bloc', 'secours', 'change', 'celui', 'dessus', 'porte', 'entree']::text[], 'TECHNIQUE', 2),
  ('cale porte à refixer (la piece est encore dans la chambre)', array['cale', 'porte', 'refixer', 'piece', 'encore', 'chambre']::text[], 'TECHNIQUE', 2),
  ('changement support lait corporel', array['changement', 'support', 'lait', 'corporel']::text[], 'TECHNIQUE', 2),
  ('difficulté à fermer la porte de chambre -', array['difficulte', 'fermer', 'porte', 'chambre']::text[], 'TECHNIQUE', 2),
  ('flexible liseuse côté droit à resserer', array['flexible', 'liseuse', 'cote', 'droit', 'resserer']::text[], 'TECHNIQUE', 2),
  ('flexible liseuse côté gauche à fixer', array['flexible', 'liseuse', 'cote', 'gauche', 'fixer']::text[], 'TECHNIQUE', 2),
  ('Fuite syphon Lavabo SDB', array['fuite', 'syphon', 'lavabo', 'sdb']::text[], 'PLOMBERIE', 2),
  ('Grand miroir côté armoire cassé', array['grand', 'miroir', 'cote', 'armoire', 'casse']::text[], 'TECHNIQUE', 2),
  ('Il faut refaire les joints mitigeur de douche', array['faut', 'refaire', 'joints', 'mitigeur', 'douche']::text[], 'TECHNIQUE', 2),
  ('joint pare douche à remplacer', array['joint', 'pare', 'douche', 'remplacer']::text[], 'TECHNIQUE', 2),
  ('Joint porte sdb', array['joint', 'porte', 'sdb']::text[], 'TECHNIQUE', 2),
  ('La porte principale ne se fermait pas bien', array['porte', 'principale', 'fermait', 'bien']::text[], 'TECHNIQUE', 2),
  ('Lèvre de douche à changer sur le côté pare douche', array['levre', 'douche', 'changer', 'cote', 'pare']::text[], 'TECHNIQUE', 2),
  ('Liseuse côté droit à changer', array['liseuse', 'cote', 'droit', 'changer']::text[], 'TECHNIQUE', 2),
  ('Liseuse côté gauche à changer', array['liseuse', 'cote', 'gauche', 'changer']::text[], 'TECHNIQUE', 2),
  ('lit cassé côté gauche', array['lit', 'casse', 'cote', 'gauche']::text[], 'TECHNIQUE', 2),
  ('lit côté droit cassé - à agrafer', array['lit', 'cote', 'droit', 'casse', 'agrafer']::text[], 'TECHNIQUE', 2),
  ('Manque porte placard ( grande) / visser aimant', array['manque', 'porte', 'placard', 'grande', 'visser', 'aimant']::text[], 'TECHNIQUE', 2),
  ('Mur gauche côté fenêtre endommagé', array['mur', 'gauche', 'cote', 'fenetre', 'endommage']::text[], 'TECHNIQUE', 2),
  ('Neon salle de repos à changer', array['neon', 'salle', 'repos', 'changer']::text[], 'TECHNIQUE', 2),
  ('Objet coincé dans la prise électrique', array['objet', 'coince', 'prise', 'electrique']::text[], 'TECHNIQUE', 2),
  ('porte du frigo à fixer', array['porte', 'frigo', 'fixer']::text[], 'TECHNIQUE', 2),
  ('recoller les cornières dorées sur les deux pilliers', array['recoller', 'cornieres', 'dorees', 'deux', 'pilliers']::text[], 'TECHNIQUE', 2),
  ('Refixer correctement le miroir grossissant au mur SDB', array['refixer', 'correctement', 'miroir', 'grossissant', 'mur', 'sdb']::text[], 'TECHNIQUE', 2),
  ('refixer la prise', array['refixer', 'prise']::text[], 'TECHNIQUE', 2),
  ('Sol du bac de douche decoller (pour montrer à l''inspecteur) puis recoller de nouveau)', array['sol', 'bac', 'douche', 'decoller', 'montrer', 'inspecteur', 'puis', 'recoller']::text[], 'PLOMBERIE', 2),
  ('spot chambre à remplacer', array['spot', 'chambre', 'remplacer']::text[], 'TECHNIQUE', 2),
  ('spot du couloir a changer', array['spot', 'couloir', 'changer']::text[], 'ELECTRIQUE', 2),
  ('télérupteur lumière néons et spots plafond sautent', array['telerupteur', 'lumiere', 'neons', 'spots', 'plafond', 'sautent']::text[], 'ELECTRIQUE', 2),
  ('télérupteur pour spots plafond à changer', array['telerupteur', 'spots', 'plafond', 'changer']::text[], 'ELECTRIQUE', 2),
  ('urgent! priorite coffre à reprogrammer', array['urgent', 'priorite', 'coffre', 'reprogrammer']::text[], 'TECHNIQUE', 2),
  ('2 Spot SDB à changer', array['spot', 'sdb', 'changer']::text[], 'ELECTRIQUE', 1),
  ('4 eme spot plafond couloir du fond à changer', array['eme', 'spot', 'plafond', 'couloir', 'fond', 'changer']::text[], 'TECHNIQUE', 1),
  ('acheter crépines pour les 2 gouttières sur le toit terrasse', array['acheter', 'crepines', 'gouttieres', 'toit', 'terrasse']::text[], 'TECHNIQUE', 1),
  ('Ampoule de l''applique à changer', array['ampoule', 'applique', 'changer']::text[], 'ELECTRIQUE', 1),
  ('Ampoule de la suspension lumineuse à côté de l''ascenseur qui clignote parfois', array['ampoule', 'suspension', 'lumineuse', 'cote', 'ascenseur', 'clignote', 'parfois']::text[], 'ELECTRIQUE', 1),
  ('Applique coté entrée à refixer correctement', array['applique', 'cote', 'entree', 'refixer', 'correctement']::text[], 'TECHNIQUE', 1),
  ('Attache mural de la porte de secours devant la porte des escaliers à fixer', array['attache', 'mural', 'porte', 'secours', 'devant', 'escaliers', 'fixer']::text[], 'TECHNIQUE', 1),
  ('Baguette d''angle noir a recollé - mur entree chambre', array['baguette', 'angle', 'noir', 'recolle', 'mur', 'entree', 'chambre']::text[], 'TECHNIQUE', 1),
  ('barre de pare douche à refixer', array['barre', 'pare', 'douche', 'refixer']::text[], 'TECHNIQUE', 1),
  ('Barrre de douche à refixer', array['barrre', 'douche', 'refixer']::text[], 'TECHNIQUE', 1),
  ('Batterie du bloc secours à changer (celui en face de l''ascenseur)', array['batterie', 'bloc', 'secours', 'changer', 'celui', 'face', 'ascenseur']::text[], 'ELECTRIQUE', 1),
  ('Batterie du bloc secours à changer (celui en face de la chambre 28)', array['batterie', 'bloc', 'secours', 'changer', 'celui', 'face', 'chambre']::text[], 'TECHNIQUE', 1),
  ('Batterie du bloc secours à changer (celui en face de la chambre 44)', array['batterie', 'bloc', 'secours', 'changer', 'celui', 'face', 'chambre']::text[], 'ELECTRIQUE', 1),
  ('Batterie du bloc secours à changer (celui en face de la chambre 48)', array['batterie', 'bloc', 'secours', 'changer', 'celui', 'face', 'chambre']::text[], 'ELECTRIQUE', 1),
  ('Batterie du bloc secours à changer (celui en face de la chambre 58)', array['batterie', 'bloc', 'secours', 'changer', 'celui', 'face', 'chambre']::text[], 'ELECTRIQUE', 1),
  ('Batterie du bloc secours à changer (celui en face de la sortie de secours)', array['batterie', 'bloc', 'secours', 'changer', 'celui', 'face', 'sortie']::text[], 'ELECTRIQUE', 1),
  ('bloc secour/batterie a changer (en face de la chambre 14)', array['bloc', 'secour', 'batterie', 'changer', 'face', 'chambre']::text[], 'ELECTRIQUE', 1),
  ('Bouton on/off pour regler la temperature non fonctionnel', array['bouton', 'off', 'regler', 'temperature', 'non', 'fonctionnel']::text[], 'TECHNIQUE', 1),
  ('Bouton pour le mitigeur douche à changer', array['bouton', 'mitigeur', 'douche', 'changer']::text[], 'TECHNIQUE', 1),
  ('Bruit provenant du panneau électrique', array['bruit', 'provenant', 'panneau', 'electrique']::text[], 'ELECTRIQUE', 1),
  ('Cache pile du coffre manquant', array['cache', 'pile', 'coffre', 'manquant']::text[], 'TECHNIQUE', 1),
  ('Cache Rosace de la poignée (exterieure) de porte à changer', array['cache', 'rosace', 'poignee', 'exterieure', 'porte', 'changer']::text[], 'TECHNIQUE', 1),
  ('Cadre de la porte de la salle de bain à fixer', array['cadre', 'porte', 'salle', 'bain', 'fixer']::text[], 'TECHNIQUE', 1),
  ('Cadre porte SDB bois - décollé du mur', array['cadre', 'porte', 'sdb', 'bois', 'decolle', 'mur']::text[], 'TECHNIQUE', 1),
  ('change bonde lavabo', array['change', 'bonde', 'lavabo']::text[], 'TECHNIQUE', 1),
  ('Changement ampoule lampe bureau', array['changement', 'ampoule', 'lampe', 'bureau']::text[], 'TECHNIQUE', 1),
  ('changement du flexible de la liseuse de droite', array['changement', 'flexible', 'liseuse', 'droite']::text[], 'TECHNIQUE', 1),
  ('changer la bonde du lavabo', array['changer', 'bonde', 'lavabo']::text[], 'PLOMBERIE', 1),
  ('Changer le miroir SDB car rouillé de l''interieur', array['changer', 'miroir', 'sdb', 'car', 'rouille', 'interieur']::text[], 'TECHNIQUE', 1),
  ('Charnière de la porte du bas à changer', array['charniere', 'porte', 'bas', 'changer']::text[], 'TECHNIQUE', 1),
  ('Coffre fort HS', array['coffre', 'fort']::text[], 'TECHNIQUE', 1),
  ('coller deux baguettes d''angle noires dans l''encadrement porte DAES', array['coller', 'deux', 'baguettes', 'angle', 'noires', 'encadrement', 'porte', 'daes']::text[], 'TECHNIQUE', 1),
  ('De l''eau coule à l''interier depuis la fenetre', array['eau', 'coule', 'interier', 'depuis', 'fenetre']::text[], 'TECHNIQUE', 1),
  ('demander à Hedi de contrôler l''état des crépines, des gouttières et de la descente de pluie et les dégager si beoin', array['demander', 'hedi', 'controler', 'etat', 'crepines', 'gouttieres', 'descente', 'pluie']::text[], 'TECHNIQUE', 1),
  ('Détection de punaises de lit au niveau de la tête de lit constaté le 30/09/25 par la societe Ecoflair', array['detection', 'punaises', 'lit', 'niveau', 'tete', 'constate', 'societe', 'ecoflair']::text[], 'TECHNIQUE', 1),
  ('ecoulement faible eau chasse d''eau vestiaire femme', array['ecoulement', 'faible', 'eau', 'chasse', 'vestiaire', 'femme']::text[], 'TECHNIQUE', 1),
  ('Evier qui coule', array['evier', 'coule']::text[], 'TECHNIQUE', 1),
  ('évier salle de pause qui fuit', array['evier', 'salle', 'pause', 'fuit']::text[], 'TECHNIQUE', 1),
  ('Faire installer la machine café -', array['installer', 'machine', 'cafe']::text[], 'TECHNIQUE', 1),
  ('Faire la pose du Lino afin d''éviter toute fuite en chambre 41', array['pose', 'lino', 'afin', 'eviter', 'toute', 'fuite', 'chambre']::text[], 'TECHNIQUE', 1),
  ('faire un trou et ensuite avec un fil de fer tirer les fils pour installer la prise pour le nouveau cadre', array['trou', 'ensuite', 'fil', 'fer', 'tirer', 'fils', 'installer', 'prise']::text[], 'ELECTRIQUE', 1),
  ('fenêtre se ferme mal', array['fenetre', 'ferme', 'mal']::text[], 'TECHNIQUE', 1),
  ('Fil de d''aspirateur à changer', array['fil', 'aspirateur', 'changer']::text[], 'TECHNIQUE', 1),
  ('Fissure constaté au plafond', array['fissure', 'constate', 'plafond']::text[], 'TECHNIQUE', 1),
  ('Flexible à changer', array['flexible', 'changer']::text[], 'TECHNIQUE', 1),
  ('flexible liseuse côté gauche à resserer', array['flexible', 'liseuse', 'cote', 'gauche', 'resserer']::text[], 'TECHNIQUE', 1),
  ('flexible liseuse côté SDB à changer', array['flexible', 'liseuse', 'cote', 'sdb', 'changer']::text[], 'TECHNIQUE', 1),
  ('Fortes odeurs constaté au niveau de la colonne, il faut trouver une solution pour reboucher', array['fortes', 'odeurs', 'constate', 'niveau', 'colonne', 'faut', 'trouver', 'solution']::text[], 'TECHNIQUE', 1),
  ('frein de chute abattant WC non fonctionnel -', array['frein', 'chute', 'abattant', 'non', 'fonctionnel']::text[], 'TECHNIQUE', 1),
  ('Fuite au niveau du bac de douche', array['fuite', 'niveau', 'bac', 'douche']::text[], 'TECHNIQUE', 1),
  ('Fuite au niveau du lave-vaisselle', array['fuite', 'niveau', 'lave', 'vaisselle']::text[], 'TECHNIQUE', 1),
  ('Fuite au niveau du spot dans la douche', array['fuite', 'niveau', 'spot', 'douche']::text[], 'TECHNIQUE', 1),
  ('Fuite constatée au niveau du deuxième lustre.', array['fuite', 'constatee', 'niveau', 'deuxieme', 'lustre']::text[], 'TECHNIQUE', 1),
  ('fuite mitigeur douche', array['fuite', 'mitigeur', 'douche']::text[], 'TECHNIQUE', 1),
  ('Il faut changer le fil du Chafing dish rond (réchaud de buffet)', array['faut', 'changer', 'fil', 'chafing', 'dish', 'rond', 'rechaud', 'buffet']::text[], 'ELECTRIQUE', 1),
  ('Il faut changer le sèche-main', array['faut', 'changer', 'seche', 'main']::text[], 'ELECTRIQUE', 1),
  ('Il faut faire les joints', array['faut', 'joints']::text[], 'TECHNIQUE', 1),
  ('Il faut fixer la barre de douche au support mural', array['faut', 'fixer', 'barre', 'douche', 'support', 'mural']::text[], 'TECHNIQUE', 1),
  ('Il faut rattacher le support du lustre au plafond.', array['faut', 'rattacher', 'support', 'lustre', 'plafond']::text[], 'TECHNIQUE', 1),
  ('Il faut repeindre les deux pots de fleurs', array['faut', 'repeindre', 'deux', 'pots', 'fleurs']::text[], 'TECHNIQUE', 1),
  ('Il manque juste le petit papier qui va à l''interieur et non le cache', array['manque', 'juste', 'petit', 'papier', 'interieur', 'non', 'cache']::text[], 'TECHNIQUE', 1),
  ('Il manque la porte du placard du bas', array['manque', 'porte', 'placard', 'bas']::text[], 'TECHNIQUE', 1),
  ('Il manque un joint sur la porte de la salle de bain et elle est désaxée', array['manque', 'joint', 'porte', 'salle', 'bain', 'elle', 'desaxee']::text[], 'TECHNIQUE', 1),
  ('Installer un interupteur', array['installer', 'interupteur']::text[], 'ELECTRIQUE', 1),
  ('inverser la VMC pour un meilleur fonctionnement', array['inverser', 'vmc', 'meilleur', 'fonctionnement']::text[], 'TECHNIQUE', 1),
  ('Joint de pare douche à changer', array['joint', 'pare', 'douche', 'changer']::text[], 'TECHNIQUE', 1),
  ('Joint de silicone à enlever pour ensuite poser des nouveaux au niveau du bac à douche', array['joint', 'silicone', 'enlever', 'ensuite', 'poser', 'nouveaux', 'niveau', 'bac']::text[], 'TECHNIQUE', 1),
  ('Joint pare douche à changer', array['joint', 'pare', 'douche', 'changer']::text[], 'TECHNIQUE', 1),
  ('Joint pare douche à changer car laisse passer l''eau', array['joint', 'pare', 'douche', 'changer', 'car', 'laisse', 'passer', 'eau']::text[], 'TECHNIQUE', 1),
  ('joint sillicone dans le bac à douche et lavabo', array['joint', 'sillicone', 'bac', 'douche', 'lavabo']::text[], 'TECHNIQUE', 1),
  ('joint sillicone lavabo', array['joint', 'sillicone', 'lavabo']::text[], 'TECHNIQUE', 1),
  ('joint sillicone lavabo douche et WC', array['joint', 'sillicone', 'lavabo', 'douche']::text[], 'TECHNIQUE', 1),
  ('joint sillicone lavabo et douche', array['joint', 'sillicone', 'lavabo', 'douche']::text[], 'TECHNIQUE', 1),
  ('La base du fauteuil doit être visée', array['base', 'fauteuil', 'doit', 'etre', 'visee']::text[], 'TECHNIQUE', 1),
  ('La chasse d''eau ne fonctionne pas', array['chasse', 'eau', 'fonctionne']::text[], 'TECHNIQUE', 1),
  ('La lumiere du miroir ne s''allume pas', array['lumiere', 'miroir', 'allume']::text[], 'ELECTRIQUE', 1),
  ('La lumiere du plafond saute - Télérupteur à changer', array['lumiere', 'plafond', 'saute', 'telerupteur', 'changer']::text[], 'ELECTRIQUE', 1),
  ('La moquette de la premiere marche en partant du haut est decollée', array['moquette', 'premiere', 'marche', 'partant', 'haut', 'decollee']::text[], 'TECHNIQUE', 1),
  ('La prise derrière la télévision ne fonctionne pas (à confirmer)', array['prise', 'derriere', 'television', 'fonctionne', 'confirmer']::text[], 'ELECTRIQUE', 1),
  ('La serrure électronique de chez dormakaba ne fonctionne plus', array['serrure', 'electronique', 'chez', 'dormakaba', 'fonctionne']::text[], 'TECHNIQUE', 1),
  ('Lampe bureau cassée - faire réparer comme M Negroni', array['lampe', 'bureau', 'cassee', 'reparer', 'comme', 'negroni']::text[], 'TECHNIQUE', 1),
  ('Lave-main à installer', array['lave', 'main', 'installer']::text[], 'ELECTRIQUE', 1),
  ('Le scratch du rideau est défaillant', array['scratch', 'rideau', 'defaillant']::text[], 'TECHNIQUE', 1),
  ('Le scratch du rideau est défaillant (SDB)', array['scratch', 'rideau', 'defaillant', 'sdb']::text[], 'TECHNIQUE', 1),
  ('liseuse gauche à resserer', array['liseuse', 'gauche', 'resserer']::text[], 'TECHNIQUE', 1),
  ('Lumière grand miroir SDB', array['lumiere', 'grand', 'miroir', 'sdb']::text[], 'ELECTRIQUE', 1),
  ('Lumiere miroir à vérifier', array['lumiere', 'miroir', 'verifier']::text[], 'ELECTRIQUE', 1),
  ('Lumiéres miroir SDB', array['lumieres', 'miroir', 'sdb']::text[], 'ELECTRIQUE', 1),
  ('Lumiéres miroir SDB à changer', array['lumieres', 'miroir', 'sdb', 'changer']::text[], 'TECHNIQUE', 1),
  ('Lumieres SDB à changer', array['lumieres', 'sdb', 'changer']::text[], 'ELECTRIQUE', 1),
  ('Lunette des WC à changer', array['lunette', 'changer']::text[], 'TECHNIQUE', 1),
  ('Manque porte placard du haut', array['manque', 'porte', 'placard', 'haut']::text[], 'TECHNIQUE', 1),
  ('mettre des cornieres noires à l''entrée de la chambe', array['mettre', 'cornieres', 'noires', 'entree', 'chambe']::text[], 'TECHNIQUE', 1),
  ('Mettre feutrine découpée sur mesure au dos de la table de chevet pour protéger le mur', array['mettre', 'feutrine', 'decoupee', 'mesure', 'dos', 'table', 'chevet', 'proteger']::text[], 'TECHNIQUE', 1),
  ('Mettre le tableau pour l''affichage obligatoire', array['mettre', 'tableau', 'affichage', 'obligatoire']::text[], 'TECHNIQUE', 1),
  ('Mettre un joint pare douche à la bonne taille car pas assez long et l''eau passe', array['mettre', 'joint', 'pare', 'douche', 'bonne', 'taille', 'car', 'assez']::text[], 'TECHNIQUE', 1),
  ('Mettre une vise sur la Porte dorée armoire (haut)', array['mettre', 'vise', 'porte', 'doree', 'armoire', 'haut']::text[], 'TECHNIQUE', 1),
  ('Nettoyage du tuyau d''évacuation du séche linge', array['nettoyage', 'tuyau', 'evacuation', 'seche', 'linge']::text[], 'TECHNIQUE', 1),
  ('passer le produit sur le parquet ( même dessoous les bacs à plantes) - produit dans la bagagerie', array['passer', 'produit', 'parquet', 'meme', 'dessoous', 'bacs', 'plantes', 'bagagerie']::text[], 'TECHNIQUE', 1),
  ('Pièce qui sert à ajuster la hauteur du pommeau de douche à viser', array['piece', 'sert', 'ajuster', 'hauteur', 'pommeau', 'douche', 'viser']::text[], 'TECHNIQUE', 1),
  ('plafond douche SDB cloqué - voir avec Kamel', array['plafond', 'douche', 'sdb', 'cloque', 'voir', 'kamel']::text[], 'TECHNIQUE', 1),
  ('Plainte rose coté lit SDB à recoller', array['plainte', 'rose', 'cote', 'lit', 'sdb', 'recoller']::text[], 'TECHNIQUE', 1),
  ('Plinthe bois chambre (Mur a gauche du lit) à recoller', array['plinthe', 'bois', 'chambre', 'mur', 'gauche', 'lit', 'recoller']::text[], 'TECHNIQUE', 1),
  ('Plinthe de la fenêtre à recoller', array['plinthe', 'fenetre', 'recoller']::text[], 'TECHNIQUE', 1),
  ('poignée porte principale à resserrer', array['poignee', 'porte', 'principale', 'resserrer']::text[], 'TECHNIQUE', 1),
  ('Pommeau de douche à changer', array['pommeau', 'douche', 'changer']::text[], 'TECHNIQUE', 1),
  ('Porte d''entrée qui grince', array['porte', 'entree', 'grince']::text[], 'TECHNIQUE', 1),
  ('Porte placard du haut à remettre / se trouve dans le local technique', array['porte', 'placard', 'haut', 'remettre', 'trouve', 'local', 'technique']::text[], 'TECHNIQUE', 1),
  ('problème de joint sur la paroi de douche car l''eau coule à travers -', array['probleme', 'joint', 'paroi', 'douche', 'car', 'eau', 'coule', 'travers']::text[], 'TECHNIQUE', 1),
  ('Rebranchement de la commande pour la tête de lit', array['rebranchement', 'commande', 'tete', 'lit']::text[], 'ELECTRIQUE', 1),
  ('Recoller la plinthe bois noire porte SDB côté SDB', array['recoller', 'plinthe', 'bois', 'noire', 'porte', 'sdb', 'cote']::text[], 'TECHNIQUE', 1),
  ('Refixer liseuse gauche', array['refixer', 'liseuse', 'gauche']::text[], 'TECHNIQUE', 1),
  ('remettre le joint noir porte coulissante SDB qui est decollé', array['remettre', 'joint', 'noir', 'porte', 'coulissante', 'sdb', 'decolle']::text[], 'TECHNIQUE', 1),
  ('Remettre le joint porte coulissante de la salle de bains', array['remettre', 'joint', 'porte', 'coulissante', 'salle', 'bains']::text[], 'TECHNIQUE', 1),
  ('Remettre le joint porte coulissante de la salle de bains - côté chambre', array['remettre', 'joint', 'porte', 'coulissante', 'salle', 'bains', 'cote', 'chambre']::text[], 'TECHNIQUE', 1),
  ('Remplacement de la bonde lavabo', array['remplacement', 'bonde', 'lavabo']::text[], 'TECHNIQUE', 1),
  ('Remplacement du télérupteur (SPOT)', array['remplacement', 'telerupteur', 'spot']::text[], 'ELECTRIQUE', 1),
  ('Remplacement du télérupteur (TETE DE LIT)', array['remplacement', 'telerupteur', 'tete', 'lit']::text[], 'ELECTRIQUE', 1),
  ('Remplacement du télérupteur (TETE DE LIT appliques)', array['remplacement', 'telerupteur', 'tete', 'lit', 'appliques']::text[], 'ELECTRIQUE', 1),
  ('Réparation de la poignée de porte du TGBT', array['reparation', 'poignee', 'porte', 'tgbt']::text[], 'TECHNIQUE', 1),
  ('réparation enduit mur blanc niveau lingerie + peinture Farid + baguettes plastiques larges et resistantes car les livreurs abîment les angles avec leurs charriots', array['reparation', 'enduit', 'mur', 'blanc', 'niveau', 'lingerie', 'peinture', 'farid']::text[], 'TECHNIQUE', 1),
  ('Réparer fissure cadre fenêtre chambre avec pâte à bois et repeindre', array['reparer', 'fissure', 'cadre', 'fenetre', 'chambre', 'pate', 'bois', 'repeindre']::text[], 'TECHNIQUE', 1),
  ('repeindre porte chambre côté extèrieur', array['repeindre', 'porte', 'chambre', 'cote', 'exterieur']::text[], 'TECHNIQUE', 1),
  ('reprendre peinture cause éclat mur dessous TV', array['reprendre', 'peinture', 'cause', 'eclat', 'mur', 'dessous']::text[], 'TECHNIQUE', 1),
  ('Resserer liseuse côté droit', array['resserer', 'liseuse', 'cote', 'droit']::text[], 'TECHNIQUE', 1),
  ('Resserer liseuse gauche', array['resserer', 'liseuse', 'gauche']::text[], 'TECHNIQUE', 1),
  ('Resserrer la poignée', array['resserrer', 'poignee']::text[], 'TECHNIQUE', 1),
  ('Resserrer la poignée de la porte d''entrée', array['resserrer', 'poignee', 'porte', 'entree']::text[], 'TECHNIQUE', 1),
  ('Robinet à changer + flexible', array['robinet', 'changer', 'flexible']::text[], 'TECHNIQUE', 1),
  ('Sèche serviette à refixer -', array['seche', 'serviette', 'refixer']::text[], 'TECHNIQUE', 1),
  ('Seche Serviette non fonctionnel', array['seche', 'serviette', 'non', 'fonctionnel']::text[], 'ELECTRIQUE', 1),
  ('sol parquet abîmé – mettre pate à bois', array['sol', 'parquet', 'abime', 'mettre', 'pate', 'bois']::text[], 'TECHNIQUE', 1),
  ('Sport à changer', array['sport', 'changer']::text[], 'TECHNIQUE', 1),
  ('Spot à changer (celui de droite)', array['spot', 'changer', 'celui', 'droite']::text[], 'ELECTRIQUE', 1),
  ('Spot à changer (celui du milieu) côté machine à café', array['spot', 'changer', 'celui', 'milieu', 'cote', 'machine', 'cafe']::text[], 'ELECTRIQUE', 1),
  ('spot à changer (celui en face de la fenêtre et a cote de l''enceinte Bose)', array['spot', 'changer', 'celui', 'face', 'fenetre', 'cote', 'enceinte', 'bose']::text[], 'ELECTRIQUE', 1),
  ('Spot à changer - côté du miroir', array['spot', 'changer', 'cote', 'miroir']::text[], 'TECHNIQUE', 1),
  ('spot à changer (le premier devant la porte d’entrée)', array['spot', 'changer', 'premier', 'devant', 'porte', 'entree']::text[], 'ELECTRIQUE', 1),
  ('Spot côté à changer à côté du miroir', array['spot', 'cote', 'changer', 'miroir']::text[], 'ELECTRIQUE', 1),
  ('Spot côté à changer derriere la réception', array['spot', 'cote', 'changer', 'derriere', 'reception']::text[], 'ELECTRIQUE', 1),
  ('Spot côté à changer devant la camera', array['spot', 'cote', 'changer', 'devant', 'camera']::text[], 'ELECTRIQUE', 1),
  ('Spot côté gauche du bar à changer', array['spot', 'cote', 'gauche', 'bar', 'changer']::text[], 'TECHNIQUE', 1),
  ('Spot dans la salle de bain', array['spot', 'salle', 'bain']::text[], 'TECHNIQUE', 1),
  ('spot dans le lobby devant la cuisine', array['spot', 'lobby', 'devant', 'cuisine']::text[], 'ELECTRIQUE', 1),
  ('Spot devant la chambre 34 à changer', array['spot', 'devant', 'chambre', 'changer']::text[], 'TECHNIQUE', 1),
  ('Spot du couloir a changer à coté de la chambre 18', array['spot', 'couloir', 'changer', 'cote', 'chambre']::text[], 'ELECTRIQUE', 1),
  ('Spot noir à changer - en face de la chambre 38', array['spot', 'noir', 'changer', 'face', 'chambre']::text[], 'TECHNIQUE', 1),
  ('Spot plafond au fond à changer', array['spot', 'plafond', 'fond', 'changer']::text[], 'ELECTRIQUE', 1),
  ('Spot plafond derrière la réception à changer', array['spot', 'plafond', 'derriere', 'reception', 'changer']::text[], 'ELECTRIQUE', 1),
  ('Spot plafond entrée HS', array['spot', 'plafond', 'entree']::text[], 'TECHNIQUE', 1),
  ('Spot plafond niveau armoire à changer', array['spot', 'plafond', 'niveau', 'armoire', 'changer']::text[], 'TECHNIQUE', 1),
  ('Spots salle de bain à changer', array['spots', 'salle', 'bain', 'changer']::text[], 'TECHNIQUE', 1),
  ('support de douche à viser', array['support', 'douche', 'viser']::text[], 'TECHNIQUE', 1),
  ('Support lait pour le corps à changer car cassé', array['support', 'lait', 'corps', 'changer', 'car', 'casse']::text[], 'TECHNIQUE', 1),
  ('Système carte pour lumière chambre cassé', array['systeme', 'carte', 'lumiere', 'chambre', 'casse']::text[], 'TECHNIQUE', 1),
  ('tablette miroir cassée pendant le remplacement + casse du grand miroir intèrieur placard', array['tablette', 'miroir', 'cassee', 'pendant', 'remplacement', 'casse', 'grand', 'interieur']::text[], 'TECHNIQUE', 1),
  ('Télérupteur à changer appliques', array['telerupteur', 'changer', 'appliques']::text[], 'ELECTRIQUE', 1),
  ('Télérupteur à changer lumière appliques murales saute', array['telerupteur', 'changer', 'lumiere', 'appliques', 'murales', 'saute']::text[], 'ELECTRIQUE', 1),
  ('Télérupteur appliques changé', array['telerupteur', 'appliques', 'change']::text[], 'TECHNIQUE', 1),
  ('Télérupteur spot et led à changer', array['telerupteur', 'spot', 'led', 'changer']::text[], 'ELECTRIQUE', 1),
  ('Toilettes bouchés', array['toilettes', 'bouches']::text[], 'TECHNIQUE', 1),
  ('trappe au plafond à refermer', array['trappe', 'plafond', 'refermer']::text[], 'ELECTRIQUE', 1),
  ('Un client suspecte la présence de punaises', array['client', 'suspecte', 'presence', 'punaises']::text[], 'TECHNIQUE', 1),
  ('URGENT - Difficulté à fermer la porte qui mene à la cour', array['urgent', 'difficulte', 'fermer', 'porte', 'mene', 'cour']::text[], 'TECHNIQUE', 1),
  ('URGENT - Joints sillicone douche - lavabo', array['urgent', 'joints', 'sillicone', 'douche', 'lavabo']::text[], 'TECHNIQUE', 1),
  ('URGENT - Joints sillicone douche - lavabo & WC', array['urgent', 'joints', 'sillicone', 'douche', 'lavabo']::text[], 'TECHNIQUE', 1),
  ('Vis du haut de la gâche à changer', array['vis', 'haut', 'gache', 'changer']::text[], 'TECHNIQUE', 1),
  ('Vis seche serviette à la reception', array['vis', 'seche', 'serviette', 'reception']::text[], 'TECHNIQUE', 1),
  ('Vis tombé de la douche à la reception - à la reception', array['vis', 'tombe', 'douche', 'reception']::text[], 'TECHNIQUE', 1),
  ('Visite contractuelle afin de vérifier si tout fonctionne correctement - Kone', array['visite', 'contractuelle', 'afin', 'verifier', 'tout', 'fonctionne', 'correctement', 'kone']::text[], 'TECHNIQUE', 1),
  ('Voilages dechirés', array['voilages', 'dechires']::text[], 'ACHATS', 1),
  ('voir comment rendre le boitier élec étanche en cas de nouvelle fuite', array['voir', 'comment', 'rendre', 'boitier', 'elec', 'etanche', 'cas', 'nouvelle']::text[], 'ELECTRIQUE', 1)
)
insert into catalogue_anomalies (libelle, mots_cles, type_id, occurrences)
select s.libelle, s.mots_cles, t.id, s.occurrences
from source s
left join types_intervention t on t.code = s.type_code
where not exists (
  select 1 from catalogue_anomalies c where c.libelle = s.libelle
);
