-- Diagnostic complet à partir du vrai export (TEST_Tech_3.xlsx, 761 anomalies,
-- colonne COMMENTAIRES — 'AnomaliesCommentaires' est le LIBELLÉ, pas un
-- commentaire, malgré son nom). Deux points.
--
-- À jouer une requête à la fois dans l'éditeur SQL de Supabase.

-- ---------------------------------------------------------------------------
-- 1. Les commentaires FANTÔMES : une ligne dans `commentaires` (donc une
--    bulle affichée) pour une anomalie dont l'export ne porte AUCUN
--    commentaire, ou porte un texte différent. L'anomalie 832 en fait
--    partie — confirmé : sa cellule COMMENTAIRES est vide dans l'export.
--    D'où vient la ligne en base, je ne sais pas encore (aucun des scripts
--    d'import ne devrait l'avoir écrite à partir de cette colonne-là) —
--    mais son contenu ne correspond à rien de réel, donc elle n'a pas sa
--    place au fil.
-- ---------------------------------------------------------------------------
with export_reel (sharepoint_id, commentaire_attendu) as (
  values
  (1229, 'Le sèche-main fonctionne après qu''Alain ait nettoyé le capteur qui était plein de poussière'),
  (1133, 'RAS'),
  (1144, 'RAS'),
  (1145, 'RAS'),
  (1146, 'RAS'),
  (1147, 'RAS'),
  (1142, 'SERAFINO · 20/05/2026 Joint défaillant côté mur droit'),
  (1080, 'Après le depart de Serafino le 15/05/26, la fuite est revenue. Le 16/05/26 Serafino est de nouveau intervenu et il pense que la fuite à cause de la pompe'),
  (1049, 'SERAFINO · 20/05/2026 Serafino a cassé le miroir'),
  (1073, 'MIGUEL · 16/06/2026 ont a changé les flexible et pompe'),
  (1039, 'Le 11/05/26 : Serafino a constaté que la fuite était à cause du bac de douche de la chambre 51 - La prochaine fois il va confirmer si la fuite est encore d’actualité'),
  (1033, 'Miguel a enlevé la base et l''a rangé dans le local technique'),
  (1037, 'La pièce à viser est dans le local technique'),
  (1029, 'Sarah aimerait que les fils soient pas du tout voyants en attendant que le lustre soit installé de nouveau - A la demande de Marie, le lustre a été réinstallé mais le cache est retenu par du scotch parce que Serafino n''a pas réussi à le clipser (quelque chose gêne)'),
  (1016, 'Pommeau changé parce qu''il y avait des traces de calcaire'),
  (1002, 'Miguel à changé le flexible mais ça fuit encore'),
  (1086, 'Après une assistance téléphonique infructueuse. Nous avons du faire venir un serrurier qui travaillait anciennement chez dormakaba qui a réparer le problème'),
  (1127, 'Passage effectué de 11h40 à 11h45 - Rien à signaler'),
  (892, 'Fait le 17/03/26 par Serafino, une deuxieme couche doit être appliquée'),
  (893, 'Nouveau flexible acheter par Serafino'),
  (895, 'Nouveau flexible acheter par Serafino'),
  (896, 'Nouveau flexible acheter par Serafino'),
  (898, 'SERAFINO · 02/06/2026 ça déjà été fait lors d''un précédent passage'),
  (492, '1'),
  (664, 'Acheter nouvel abattant'),
  (704, 'Petite cuillère trouvée dans le siphon'),
  (786, 'voir stock B pour retrouver ref - @ Sarah le 6/01 et relance le 13/01'),
  (589, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (1128, 'L’ascenseur indiqué hors service et se trouvait bloqué au niveau 0. Il s’est ensuite remis à fonctionner, mais de manière aléatoire. J’ai donc choisi de le bloquer au niveau -1'),
  (379, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (716, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (744, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (494, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (642, 'Changement de la poignée de fenêtre'),
  (705, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (819, 'Le 16/11/25 Hedi a changé une seule batterie sur les deux et pour l''instant tout semble en ordre - je n''ai pas modifé le stock parce que d''après lui la batterie fonctionne encore à confirmer'),
  (376, 'Détection de punaises par la société Ecoflair - RAS'),
  (384, 'Détection de punaises par la société Ecoflair - RAS'),
  (394, 'Détection de punaises par la société Ecoflair - RAS'),
  (407, 'Détection de punaises par la société Ecoflair - RAS'),
  (420, 'Détection de punaises par la société Ecoflair - RAS'),
  (433, 'Détection de punaises par la société Ecoflair - RAS'),
  (444, 'Détection de punaises par la société Ecoflair - RAS'),
  (452, 'Détection de punaises par la société Ecoflair - RAS'),
  (465, 'Détection de punaises par la société Ecoflair - RAS'),
  (480, 'Détection de punaises par la société Ecoflair - RAS'),
  (488, 'Détection de punaises par la société Ecoflair - RAS'),
  (500, 'Détection de punaises par la société Ecoflair - RAS'),
  (514, 'Détection de punaises par la société Ecoflair - RAS'),
  (520, 'Détection de punaises par la société Ecoflair - RAS'),
  (527, 'Détection de punaises par la société Ecoflair - RAS'),
  (542, 'Détection de punaises par la société Ecoflair - RAS'),
  (556, 'Détection de punaises par la société Ecoflair - RAS'),
  (563, 'Détection de punaises par la société Ecoflair - RAS'),
  (570, 'Détection de punaises par la société Ecoflair - RAS'),
  (581, 'Détection de punaises par la société Ecoflair - RAS'),
  (597, 'Détection de punaises par la société Ecoflair - RAS'),
  (605, 'Détection de punaises par la société Ecoflair - RAS'),
  (618, 'Détection de punaises par la société Ecoflair - RAS'),
  (631, 'Détection de punaises par la société Ecoflair - RAS'),
  (640, 'Détection de punaises par la société Ecoflair - RAS'),
  (648, 'Détection de punaises par la société Ecoflair - RAS'),
  (661, 'Détection de punaises par la société Ecoflair - RAS'),
  (681, 'Détection de punaises par la société Ecoflair - RAS'),
  (697, 'Détection de punaises par la société Ecoflair - RAS'),
  (713, 'Détection de punaises par la société Ecoflair - RAS'),
  (722, 'Détection de punaises par la société Ecoflair - RAS'),
  (736, 'Détection de punaises par la société Ecoflair - RAS'),
  (759, 'Le 30/09/25 - Punaises constaté au niveau de la tête de lit - Le 01/10/25 Rachid a fait un traitement'),
  (760, 'Détection de punaises par la société Ecoflair - Punaises constaté au niveau de la tête de lit'),
  (769, 'Détection de punaises par la société Ecoflair - RAS'),
  (782, 'Détection de punaises par la société Ecoflair - RAS'),
  (795, 'Détection de punaises par la société Ecoflair - RAS'),
  (811, 'Détection de punaises par la société Ecoflair - RAS'),
  (510, 'Marie le prend chez Europroh dans les jours à venir - devis en cours'),
  (503, 'pas d''agrafeuse lors du passage du 18/09 - attente prochain passage'),
  (686, 'selon Hedi, l''eau coule toujours car il faudrait changer tout le mitigeur, pas juste le flexible - passage du 18.09'),
  (676, 'Erreur lors de la commande du 09/09/25 - Télérupteur électrique au lieu de mécaniques'),
  (547, 'prévoir le changement du connecteur de raccordement car ne tient plus - Le 26/09/25 Hedi ne constacte aucun probléme à confirmer'),
  (621, 'qqun présent en chambre connecteur pas changé / juste'),
  (1129, 'Le problème était lié à de la poussière'),
  (591, 'nécéssite le changement complet du mécanisme de chasse d''eau selon passage Hedi du 18.09 - Finalement joints effectués lors du passage du 20.09'),
  (448, 'Selon passage Hedi du 18.09, changelment total du système de chasse d''eau - suite passage du 20/09 - joints effectués'),
  (475, 'nécéssite le changement complet du mécanisme de chasse d''eau selon passage Hedi le 18.09 Finalement joints effectués passage Hedi du 20.09'),
  (421, 'flexible remplacé'),
  (879, 'Il faut acheter un robinet'),
  (733, 'Erreur lors de la commande du 09/09/25 - Télérupteur électrique au lieu de mécaniques'),
  (839, 'Alain l''a déconnecté et reconnecté le 4/08 - clignote en vert pour dire qu''il se charge. Normalement clignotement disparaît sous 24h - le clignotement est encore'),
  (852, 'OK par Alain attention, la peinture a été abîmée par el plombier - à refaire'),
  (853, 'Système de tube avec trous pour évac de l''eau avant d''arriver au boîtier - att retour Alain début Sept avec achat du matériel - Hedi a bouché des trous avec un plastique noir et il n''arrive pas à accéder côté clim - voir si M Negroni est ok avec les photos - Le 12/09/25 Alain a installé un tuyau qui dévie l''eau mais le tuyau n''est pas assez long donc lors de sa prochaine intervention il apportera un plus grand'),
  (496, 'Refait le 8/08 car porte ne ferme toujours pas en date du 8/08 ( vu avec Taïbi) refait le 18/09 par Hedi'),
  (533, 'Rodica l''a débouché le 31/07/25'),
  (395, 'Ok mais pour les autres chambres, il n''est pas possible de dévisse - il faudrait changer le mitigeur'),
  (827, 'PB non constaté, changement de l''ampoule par précaution'),
  (784, 'Hedi passage le 16/11 mais ne fonctionne toujorus pas'),
  (833, 'Fil acheté sur FILFA'),
  (599, 'prévoir le changement du connecteur de raccordement car ne tient plus - att retour Alain avec fourniture - vu le 4/08'),
  (571, 'flexible remplacé'),
  (813, 'joint'),
  (881, 'Remise en état de la douchette ainsi que le flexible et le robinet - victoria a trouvé un robinet ainsi qu''un flexible en stock'),
  (559, 'N''a pas eu besoin de changer le flexible - joint effectué'),
  (984, 'Fait par Alain le 16/04/26 mais il faut toujours deux cartes pour que ça fonctionne'),
  (829, 'appeler Kamel - à valider avec Marie & Andrea'),
  (598, 'Le 29/04/25 Juan a tenté de le faire mais n''avait pas le materiel necessaire Pas d''agrafeuse lors du passage hedi le 18.09'),
  (455, 'Hedi a "réparer l''économisseur" en recollant les piéces defaillantes à la colle forte. Aucun remplacement à été fait'),
  (477, 'contrôle le 14 Avril 2025, plus de pb apparent'),
  (872, 'à commander dormakaba Sarah ? - en déjà en stock'),
  (443, 'Apres verification par Victoria, il faut fixer de nouveau le flexible parce que ça fuit encore - Victoria l''a changé le 15/04/25 il faut juste verifier si c''est bien fait'),
  (871, 'Pb d''electricité - pas de jus, voir avec Alain - le 21/05/25 alain a changé le transfo'),
  (545, 'att commande et livraison télérupteurs Alain - le 21/05/25 alain a ramener les télérupteurs (aucune sortie de stock), ils seront peut etre inclus dans la facture'),
  (740, 'le 21/05/25 alain a ramener les télérupteurs (aucune sortie de stock), ils seront peut etre inclus dans la facture'),
  (381, 'pas d''agrafeuse sur lui le 18.09 - prochain passage'),
  (436, 'Pas besoin selon visite HEDI le 5/08 -Pas de solution perenne / baghuette propre'),
  (655, 'Aucune fuite constatée lors du passage du 08/04/25'),
  (698, '26/09/25 - Hedi dit que quelqu''un l''a lors de son passage,'),
  (408, 'selon Hedi, pas possible de dévisser - il faudrait changer le mitigeur complet'),
  (410, 'A voir avec Marie & Andrea si on change le miroir'),
  (422, 'selon Hedi, pas possible de dévisser - il faudrait changer le mitigeur complet'),
  (431, 'Hedi aurait remis des joints mais pas ce que nous avons demandé - PAS FAIT - vérif le 15 AOUT - le 18/09/25 Hedi indique que le joint n''est pas utile et nécessiterait de retirer toute la porte pour rien - trop d''heures de travail'),
  (449, 'propre selon Hedi pas besoin de refaire - visite le 5 Aout'),
  (454, 'RAS selon visite HEDI le 5/08 ( à revérifier par Victoria)'),
  (468, 'RAS selon visite HEDI le 5/08 ( à revérifier par Victoria) - il faut acheter un joint pour que nous puissions faire tenir la pomme de douche'),
  (608, 'prévoir le changement du connecteur de raccordement car ne tient plus - att retour Alain avec fourniture - vu le 4/08'),
  (600, 'Récupérée par Farid le 17/02 pour emmener à l''atelier'),
  (404, 'lumière fonctionne lors de la visite de Farid'),
  (741, 'déjà fait selon visite Hedi le 05/08'),
  (765, 'Vérifié par Victoria, il n''y avait plus besoin de le faire'),
  (434, 'Repasser dessus car l''aimant vissé ne tient pas, il faut ajouter une vis ou refixer correctement'),
  (461, 'OK REMISE EN CHAMBRE'),
  (537, 'OK REMISE EN CHAMBRE'),
  (638, 'OK REMISE EN CHAMBRE'),
  (742, 'La porte à été remise le 17/02 mais il manque la vis pour faire tenir l''aimant'),
  (752, 'OK REMISE EN CHAMBRE'),
  (771, 'Réparation M Negroni ok, manque juste l''ampoule ( lampe dans le local technique) - @ réception le 18/02 car nous avons trouvé une lampe fonctionnelle en 55... Nous ne savons pas où mettre la lampe qui se trouve au sous sol'),
  (777, 'OK REMISE EN CHAMBRE'),
  (846, 'A la demande de Mr Negroni - fait par Alain'),
  (851, 'Vu entre Marie et Alain pour l''intervention'),
  (557, 'Suite passage du 08/04/25 pas besoin de changer mais juste à resserer'),
  (620, 'test prévu dans cette chambre avec Serafino lors de son prochain passage - vu avec Sarah & Serafino le 6/01'),
  (983, 'Dégâts fait par le technicien Avir'),
  (415, 'Apparemment déjà fait'),
  (428, 'noté fait le 30/01 mais pas fait'),
  (814, 'Voir avec Serafino pour vérifier l''état de la VMC et s''il trouve le pb lors de son passage du mardi 13 -'),
  (842, 'EN COMMANDE PAR ANDREA - reçu le 14/03/25 par Victoria'),
  (490, 'Apres verifications le 19/02/25 par Victoria - Le miroir n''a pas été correctement visé - ok Hedi est repassé dessus le 05/08 ( non vérifié)'),
  (491, '6 baguettes joints neuves déposées par M Negroni le 24/01 pour pare douches dans la lingerie -'),
  (524, 'Apres verifications le 19/02/25 par Victoria - resseré le 08/04/25'),
  (607, 'Collé ok - faire le joint et repeindre la plinthe - selon Hedi déjà fait lors du passage du 18.09'),
  (684, 'fait le 21/01 mais fuit de nouveau le 24/01 - 30/01/25, le joint à été enlevé par Farid et Mr Jacques'),
  (732, 'Victoria a contaster qu''il fallait de nouveau le faire le 15/02/25'),
  (738, 'le miroir a dû être déplacé donc trous apparents, refaire peinture'),
  (560, 'telerupteur mecanique - L''hotel test des télérupteurs mecaniques à la place des télérupteurs electriques'),
  (481, 'Faire l''étanchéité enn attendant l''arrivée de M Negroni pour les travaux - fait par Hedi le 08/08'),
  (549, 'Changement commande et sonde ok'),
  (651, 'Faire l''étanchéité enn attendant l''arrivée de M Negroni pour les travaux'),
  (687, 'prévoir le changement du connecteur de raccordement car ne tient plus - att retour Alain avec fourniture - vu le 4/08'),
  (724, '30/01/25 - Farid dit que lui ne peut pas le faire - Le 24/06/25 Hedi à acheté une protaction en attendant de pouvoir le changer- étanchéité faite par Hedi en Juillet'),
  (439, 'à Verifier avec Victoria'),
  (476, 'télérupteur mécanique - L''hotel test des télérupteurs mecaniques à la place des télérupteurs electriques'),
  (683, 'Alain a constaté le 10/12/24 que les branchements étaient abaissés'),
  (438, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (541, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (680, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (712, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (375, 'Détection de punaises par la société Ecoflair - RAS'),
  (383, 'Détection de punaises par la société Ecoflair - RAS'),
  (393, 'Détection de punaises par la société Ecoflair - RAS'),
  (405, 'Détection de punaises par la société Ecoflair - RAS'),
  (418, 'Détection de punaises par la société Ecoflair - RAS'),
  (432, 'Détection de punaises par la société Ecoflair - RAS'),
  (437, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (445, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (451, 'Détection de punaises par la société Ecoflair - RAS'),
  (464, 'Détection de punaises par la société Ecoflair - RAS'),
  (479, 'Détection de punaises par la société Ecoflair - RAS'),
  (487, 'Détection de punaises par la société Ecoflair - RAS'),
  (499, 'Détection de punaises par la société Ecoflair - RAS'),
  (513, 'Détection de punaises par la société Ecoflair - RAS'),
  (519, 'Détection de punaises par la société Ecoflair - RAS'),
  (526, 'Détection de punaises par la société Ecoflair - RAS'),
  (540, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (543, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (555, 'Détection de punaises par la société Ecoflair - RAS'),
  (562, 'Détection de punaises par la société Ecoflair - RAS'),
  (569, 'Détection de punaises par la société Ecoflair - RAS'),
  (580, 'Détection de punaises par la société Ecoflair - RAS'),
  (596, 'Détection de punaises par la société Ecoflair - RAS'),
  (604, 'Détection de punaises par la société Ecoflair - RAS'),
  (617, 'Détection de punaises par la société Ecoflair - RAS'),
  (630, 'Détection de punaises par la société Ecoflair - RAS'),
  (639, 'Détection de punaises par la société Ecoflair - RAS'),
  (647, 'Détection de punaises par la société Ecoflair - RAS'),
  (660, 'Détection de punaises par la société Ecoflair - RAS'),
  (679, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (682, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (696, 'Détection de punaises par la société Ecoflair - RAS'),
  (711, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (714, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (721, 'Détection de punaises par la société Ecoflair - RAS'),
  (735, 'Détection de punaises par la société Ecoflair - RAS'),
  (753, 'Détection de punaises par la société Ecoflair - RAS'),
  (768, 'Détection de punaises par la société Ecoflair - RAS'),
  (781, 'Détection de punaises par la société Ecoflair - RAS'),
  (794, 'Détection de punaises par la société Ecoflair - RAS'),
  (810, 'Détection de punaises par la société Ecoflair - RAS'),
  (859, 'Détection de punaises par la société Ecoflair - RAS'),
  (675, 'Après vérification à l''œil nu par Victoria, aucune trace de punaises')
)
select a.sharepoint_id, a.description, c.id as commentaire_id,
       c.texte as "commentaire en base", er.commentaire_attendu,
       case
         when er.sharepoint_id is null then 'FANTOME : aucun commentaire dans l''export'
         else 'TEXTE DIFFERENT de l''export'
       end as diagnostic
  from commentaires c
  join anomalies a on a.id = c.anomalie_id
  left join export_reel er on er.sharepoint_id = a.sharepoint_id
 where c.origine = 'utilisateur'
   and a.sharepoint_id is not null
   and (er.sharepoint_id is null or er.commentaire_attendu <> c.texte)
 order by a.sharepoint_id;

-- ---------------------------------------------------------------------------
-- 2. Le nettoyage — SEULEMENT les FANTÔMES (jamais un texte différent : ça
--    peut être une correction faite depuis l'application, à regarder à la
--    main). Relire le résultat de la requête 1 d'abord : elle doit ne
--    montrer QUE des 'FANTOME', sinon retirer la clause 'TEXTE DIFFERENT'
--    ci-dessous n'est plus vrai et il faut trier à la main.
-- ---------------------------------------------------------------------------
with export_reel (sharepoint_id, commentaire_attendu) as (
  values
  (1229, 'Le sèche-main fonctionne après qu''Alain ait nettoyé le capteur qui était plein de poussière'),
  (1133, 'RAS'),
  (1144, 'RAS'),
  (1145, 'RAS'),
  (1146, 'RAS'),
  (1147, 'RAS'),
  (1142, 'SERAFINO · 20/05/2026 Joint défaillant côté mur droit'),
  (1080, 'Après le depart de Serafino le 15/05/26, la fuite est revenue. Le 16/05/26 Serafino est de nouveau intervenu et il pense que la fuite à cause de la pompe'),
  (1049, 'SERAFINO · 20/05/2026 Serafino a cassé le miroir'),
  (1073, 'MIGUEL · 16/06/2026 ont a changé les flexible et pompe'),
  (1039, 'Le 11/05/26 : Serafino a constaté que la fuite était à cause du bac de douche de la chambre 51 - La prochaine fois il va confirmer si la fuite est encore d’actualité'),
  (1033, 'Miguel a enlevé la base et l''a rangé dans le local technique'),
  (1037, 'La pièce à viser est dans le local technique'),
  (1029, 'Sarah aimerait que les fils soient pas du tout voyants en attendant que le lustre soit installé de nouveau - A la demande de Marie, le lustre a été réinstallé mais le cache est retenu par du scotch parce que Serafino n''a pas réussi à le clipser (quelque chose gêne)'),
  (1016, 'Pommeau changé parce qu''il y avait des traces de calcaire'),
  (1002, 'Miguel à changé le flexible mais ça fuit encore'),
  (1086, 'Après une assistance téléphonique infructueuse. Nous avons du faire venir un serrurier qui travaillait anciennement chez dormakaba qui a réparer le problème'),
  (1127, 'Passage effectué de 11h40 à 11h45 - Rien à signaler'),
  (892, 'Fait le 17/03/26 par Serafino, une deuxieme couche doit être appliquée'),
  (893, 'Nouveau flexible acheter par Serafino'),
  (895, 'Nouveau flexible acheter par Serafino'),
  (896, 'Nouveau flexible acheter par Serafino'),
  (898, 'SERAFINO · 02/06/2026 ça déjà été fait lors d''un précédent passage'),
  (492, '1'),
  (664, 'Acheter nouvel abattant'),
  (704, 'Petite cuillère trouvée dans le siphon'),
  (786, 'voir stock B pour retrouver ref - @ Sarah le 6/01 et relance le 13/01'),
  (589, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (1128, 'L’ascenseur indiqué hors service et se trouvait bloqué au niveau 0. Il s’est ensuite remis à fonctionner, mais de manière aléatoire. J’ai donc choisi de le bloquer au niveau -1'),
  (379, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (716, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (744, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (494, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (642, 'Changement de la poignée de fenêtre'),
  (705, 'Au lieu de les agrafer ensemble, Mr Serafino les a viser'),
  (819, 'Le 16/11/25 Hedi a changé une seule batterie sur les deux et pour l''instant tout semble en ordre - je n''ai pas modifé le stock parce que d''après lui la batterie fonctionne encore à confirmer'),
  (376, 'Détection de punaises par la société Ecoflair - RAS'),
  (384, 'Détection de punaises par la société Ecoflair - RAS'),
  (394, 'Détection de punaises par la société Ecoflair - RAS'),
  (407, 'Détection de punaises par la société Ecoflair - RAS'),
  (420, 'Détection de punaises par la société Ecoflair - RAS'),
  (433, 'Détection de punaises par la société Ecoflair - RAS'),
  (444, 'Détection de punaises par la société Ecoflair - RAS'),
  (452, 'Détection de punaises par la société Ecoflair - RAS'),
  (465, 'Détection de punaises par la société Ecoflair - RAS'),
  (480, 'Détection de punaises par la société Ecoflair - RAS'),
  (488, 'Détection de punaises par la société Ecoflair - RAS'),
  (500, 'Détection de punaises par la société Ecoflair - RAS'),
  (514, 'Détection de punaises par la société Ecoflair - RAS'),
  (520, 'Détection de punaises par la société Ecoflair - RAS'),
  (527, 'Détection de punaises par la société Ecoflair - RAS'),
  (542, 'Détection de punaises par la société Ecoflair - RAS'),
  (556, 'Détection de punaises par la société Ecoflair - RAS'),
  (563, 'Détection de punaises par la société Ecoflair - RAS'),
  (570, 'Détection de punaises par la société Ecoflair - RAS'),
  (581, 'Détection de punaises par la société Ecoflair - RAS'),
  (597, 'Détection de punaises par la société Ecoflair - RAS'),
  (605, 'Détection de punaises par la société Ecoflair - RAS'),
  (618, 'Détection de punaises par la société Ecoflair - RAS'),
  (631, 'Détection de punaises par la société Ecoflair - RAS'),
  (640, 'Détection de punaises par la société Ecoflair - RAS'),
  (648, 'Détection de punaises par la société Ecoflair - RAS'),
  (661, 'Détection de punaises par la société Ecoflair - RAS'),
  (681, 'Détection de punaises par la société Ecoflair - RAS'),
  (697, 'Détection de punaises par la société Ecoflair - RAS'),
  (713, 'Détection de punaises par la société Ecoflair - RAS'),
  (722, 'Détection de punaises par la société Ecoflair - RAS'),
  (736, 'Détection de punaises par la société Ecoflair - RAS'),
  (759, 'Le 30/09/25 - Punaises constaté au niveau de la tête de lit - Le 01/10/25 Rachid a fait un traitement'),
  (760, 'Détection de punaises par la société Ecoflair - Punaises constaté au niveau de la tête de lit'),
  (769, 'Détection de punaises par la société Ecoflair - RAS'),
  (782, 'Détection de punaises par la société Ecoflair - RAS'),
  (795, 'Détection de punaises par la société Ecoflair - RAS'),
  (811, 'Détection de punaises par la société Ecoflair - RAS'),
  (510, 'Marie le prend chez Europroh dans les jours à venir - devis en cours'),
  (503, 'pas d''agrafeuse lors du passage du 18/09 - attente prochain passage'),
  (686, 'selon Hedi, l''eau coule toujours car il faudrait changer tout le mitigeur, pas juste le flexible - passage du 18.09'),
  (676, 'Erreur lors de la commande du 09/09/25 - Télérupteur électrique au lieu de mécaniques'),
  (547, 'prévoir le changement du connecteur de raccordement car ne tient plus - Le 26/09/25 Hedi ne constacte aucun probléme à confirmer'),
  (621, 'qqun présent en chambre connecteur pas changé / juste'),
  (1129, 'Le problème était lié à de la poussière'),
  (591, 'nécéssite le changement complet du mécanisme de chasse d''eau selon passage Hedi du 18.09 - Finalement joints effectués lors du passage du 20.09'),
  (448, 'Selon passage Hedi du 18.09, changelment total du système de chasse d''eau - suite passage du 20/09 - joints effectués'),
  (475, 'nécéssite le changement complet du mécanisme de chasse d''eau selon passage Hedi le 18.09 Finalement joints effectués passage Hedi du 20.09'),
  (421, 'flexible remplacé'),
  (879, 'Il faut acheter un robinet'),
  (733, 'Erreur lors de la commande du 09/09/25 - Télérupteur électrique au lieu de mécaniques'),
  (839, 'Alain l''a déconnecté et reconnecté le 4/08 - clignote en vert pour dire qu''il se charge. Normalement clignotement disparaît sous 24h - le clignotement est encore'),
  (852, 'OK par Alain attention, la peinture a été abîmée par el plombier - à refaire'),
  (853, 'Système de tube avec trous pour évac de l''eau avant d''arriver au boîtier - att retour Alain début Sept avec achat du matériel - Hedi a bouché des trous avec un plastique noir et il n''arrive pas à accéder côté clim - voir si M Negroni est ok avec les photos - Le 12/09/25 Alain a installé un tuyau qui dévie l''eau mais le tuyau n''est pas assez long donc lors de sa prochaine intervention il apportera un plus grand'),
  (496, 'Refait le 8/08 car porte ne ferme toujours pas en date du 8/08 ( vu avec Taïbi) refait le 18/09 par Hedi'),
  (533, 'Rodica l''a débouché le 31/07/25'),
  (395, 'Ok mais pour les autres chambres, il n''est pas possible de dévisse - il faudrait changer le mitigeur'),
  (827, 'PB non constaté, changement de l''ampoule par précaution'),
  (784, 'Hedi passage le 16/11 mais ne fonctionne toujorus pas'),
  (833, 'Fil acheté sur FILFA'),
  (599, 'prévoir le changement du connecteur de raccordement car ne tient plus - att retour Alain avec fourniture - vu le 4/08'),
  (571, 'flexible remplacé'),
  (813, 'joint'),
  (881, 'Remise en état de la douchette ainsi que le flexible et le robinet - victoria a trouvé un robinet ainsi qu''un flexible en stock'),
  (559, 'N''a pas eu besoin de changer le flexible - joint effectué'),
  (984, 'Fait par Alain le 16/04/26 mais il faut toujours deux cartes pour que ça fonctionne'),
  (829, 'appeler Kamel - à valider avec Marie & Andrea'),
  (598, 'Le 29/04/25 Juan a tenté de le faire mais n''avait pas le materiel necessaire Pas d''agrafeuse lors du passage hedi le 18.09'),
  (455, 'Hedi a "réparer l''économisseur" en recollant les piéces defaillantes à la colle forte. Aucun remplacement à été fait'),
  (477, 'contrôle le 14 Avril 2025, plus de pb apparent'),
  (872, 'à commander dormakaba Sarah ? - en déjà en stock'),
  (443, 'Apres verification par Victoria, il faut fixer de nouveau le flexible parce que ça fuit encore - Victoria l''a changé le 15/04/25 il faut juste verifier si c''est bien fait'),
  (871, 'Pb d''electricité - pas de jus, voir avec Alain - le 21/05/25 alain a changé le transfo'),
  (545, 'att commande et livraison télérupteurs Alain - le 21/05/25 alain a ramener les télérupteurs (aucune sortie de stock), ils seront peut etre inclus dans la facture'),
  (740, 'le 21/05/25 alain a ramener les télérupteurs (aucune sortie de stock), ils seront peut etre inclus dans la facture'),
  (381, 'pas d''agrafeuse sur lui le 18.09 - prochain passage'),
  (436, 'Pas besoin selon visite HEDI le 5/08 -Pas de solution perenne / baghuette propre'),
  (655, 'Aucune fuite constatée lors du passage du 08/04/25'),
  (698, '26/09/25 - Hedi dit que quelqu''un l''a lors de son passage,'),
  (408, 'selon Hedi, pas possible de dévisser - il faudrait changer le mitigeur complet'),
  (410, 'A voir avec Marie & Andrea si on change le miroir'),
  (422, 'selon Hedi, pas possible de dévisser - il faudrait changer le mitigeur complet'),
  (431, 'Hedi aurait remis des joints mais pas ce que nous avons demandé - PAS FAIT - vérif le 15 AOUT - le 18/09/25 Hedi indique que le joint n''est pas utile et nécessiterait de retirer toute la porte pour rien - trop d''heures de travail'),
  (449, 'propre selon Hedi pas besoin de refaire - visite le 5 Aout'),
  (454, 'RAS selon visite HEDI le 5/08 ( à revérifier par Victoria)'),
  (468, 'RAS selon visite HEDI le 5/08 ( à revérifier par Victoria) - il faut acheter un joint pour que nous puissions faire tenir la pomme de douche'),
  (608, 'prévoir le changement du connecteur de raccordement car ne tient plus - att retour Alain avec fourniture - vu le 4/08'),
  (600, 'Récupérée par Farid le 17/02 pour emmener à l''atelier'),
  (404, 'lumière fonctionne lors de la visite de Farid'),
  (741, 'déjà fait selon visite Hedi le 05/08'),
  (765, 'Vérifié par Victoria, il n''y avait plus besoin de le faire'),
  (434, 'Repasser dessus car l''aimant vissé ne tient pas, il faut ajouter une vis ou refixer correctement'),
  (461, 'OK REMISE EN CHAMBRE'),
  (537, 'OK REMISE EN CHAMBRE'),
  (638, 'OK REMISE EN CHAMBRE'),
  (742, 'La porte à été remise le 17/02 mais il manque la vis pour faire tenir l''aimant'),
  (752, 'OK REMISE EN CHAMBRE'),
  (771, 'Réparation M Negroni ok, manque juste l''ampoule ( lampe dans le local technique) - @ réception le 18/02 car nous avons trouvé une lampe fonctionnelle en 55... Nous ne savons pas où mettre la lampe qui se trouve au sous sol'),
  (777, 'OK REMISE EN CHAMBRE'),
  (846, 'A la demande de Mr Negroni - fait par Alain'),
  (851, 'Vu entre Marie et Alain pour l''intervention'),
  (557, 'Suite passage du 08/04/25 pas besoin de changer mais juste à resserer'),
  (620, 'test prévu dans cette chambre avec Serafino lors de son prochain passage - vu avec Sarah & Serafino le 6/01'),
  (983, 'Dégâts fait par le technicien Avir'),
  (415, 'Apparemment déjà fait'),
  (428, 'noté fait le 30/01 mais pas fait'),
  (814, 'Voir avec Serafino pour vérifier l''état de la VMC et s''il trouve le pb lors de son passage du mardi 13 -'),
  (842, 'EN COMMANDE PAR ANDREA - reçu le 14/03/25 par Victoria'),
  (490, 'Apres verifications le 19/02/25 par Victoria - Le miroir n''a pas été correctement visé - ok Hedi est repassé dessus le 05/08 ( non vérifié)'),
  (491, '6 baguettes joints neuves déposées par M Negroni le 24/01 pour pare douches dans la lingerie -'),
  (524, 'Apres verifications le 19/02/25 par Victoria - resseré le 08/04/25'),
  (607, 'Collé ok - faire le joint et repeindre la plinthe - selon Hedi déjà fait lors du passage du 18.09'),
  (684, 'fait le 21/01 mais fuit de nouveau le 24/01 - 30/01/25, le joint à été enlevé par Farid et Mr Jacques'),
  (732, 'Victoria a contaster qu''il fallait de nouveau le faire le 15/02/25'),
  (738, 'le miroir a dû être déplacé donc trous apparents, refaire peinture'),
  (560, 'telerupteur mecanique - L''hotel test des télérupteurs mecaniques à la place des télérupteurs electriques'),
  (481, 'Faire l''étanchéité enn attendant l''arrivée de M Negroni pour les travaux - fait par Hedi le 08/08'),
  (549, 'Changement commande et sonde ok'),
  (651, 'Faire l''étanchéité enn attendant l''arrivée de M Negroni pour les travaux'),
  (687, 'prévoir le changement du connecteur de raccordement car ne tient plus - att retour Alain avec fourniture - vu le 4/08'),
  (724, '30/01/25 - Farid dit que lui ne peut pas le faire - Le 24/06/25 Hedi à acheté une protaction en attendant de pouvoir le changer- étanchéité faite par Hedi en Juillet'),
  (439, 'à Verifier avec Victoria'),
  (476, 'télérupteur mécanique - L''hotel test des télérupteurs mecaniques à la place des télérupteurs electriques'),
  (683, 'Alain a constaté le 10/12/24 que les branchements étaient abaissés'),
  (438, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (541, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (680, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (712, 'Le 11/10/24 Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué - Le 05/11/2024 a été fait une demande de vérification pour voir si le traitement chimique+ le traitement à froid ont fonctionné'),
  (375, 'Détection de punaises par la société Ecoflair - RAS'),
  (383, 'Détection de punaises par la société Ecoflair - RAS'),
  (393, 'Détection de punaises par la société Ecoflair - RAS'),
  (405, 'Détection de punaises par la société Ecoflair - RAS'),
  (418, 'Détection de punaises par la société Ecoflair - RAS'),
  (432, 'Détection de punaises par la société Ecoflair - RAS'),
  (437, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (445, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (451, 'Détection de punaises par la société Ecoflair - RAS'),
  (464, 'Détection de punaises par la société Ecoflair - RAS'),
  (479, 'Détection de punaises par la société Ecoflair - RAS'),
  (487, 'Détection de punaises par la société Ecoflair - RAS'),
  (499, 'Détection de punaises par la société Ecoflair - RAS'),
  (513, 'Détection de punaises par la société Ecoflair - RAS'),
  (519, 'Détection de punaises par la société Ecoflair - RAS'),
  (526, 'Détection de punaises par la société Ecoflair - RAS'),
  (540, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (543, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (555, 'Détection de punaises par la société Ecoflair - RAS'),
  (562, 'Détection de punaises par la société Ecoflair - RAS'),
  (569, 'Détection de punaises par la société Ecoflair - RAS'),
  (580, 'Détection de punaises par la société Ecoflair - RAS'),
  (596, 'Détection de punaises par la société Ecoflair - RAS'),
  (604, 'Détection de punaises par la société Ecoflair - RAS'),
  (617, 'Détection de punaises par la société Ecoflair - RAS'),
  (630, 'Détection de punaises par la société Ecoflair - RAS'),
  (639, 'Détection de punaises par la société Ecoflair - RAS'),
  (647, 'Détection de punaises par la société Ecoflair - RAS'),
  (660, 'Détection de punaises par la société Ecoflair - RAS'),
  (679, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (682, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (696, 'Détection de punaises par la société Ecoflair - RAS'),
  (711, 'Détection de punaises par la société Ecoflair - Punaises constaté'),
  (714, 'Le 11/10/24 - Punaises constaté au niveau de la tête de lit - Le 12/10/24 Rachid a fait un traitement chimique - Le 21/10/24 un deuxieme passage a été fait, cette fois ci c''est un traitement à froid qui a été appliqué'),
  (721, 'Détection de punaises par la société Ecoflair - RAS'),
  (735, 'Détection de punaises par la société Ecoflair - RAS'),
  (753, 'Détection de punaises par la société Ecoflair - RAS'),
  (768, 'Détection de punaises par la société Ecoflair - RAS'),
  (781, 'Détection de punaises par la société Ecoflair - RAS'),
  (794, 'Détection de punaises par la société Ecoflair - RAS'),
  (810, 'Détection de punaises par la société Ecoflair - RAS'),
  (859, 'Détection de punaises par la société Ecoflair - RAS'),
  (675, 'Après vérification à l''œil nu par Victoria, aucune trace de punaises')
)
delete from commentaires c
 using anomalies a
 where c.anomalie_id = a.id
   and c.origine = 'utilisateur'
   and a.sharepoint_id is not null
   and not exists (
     select 1 from export_reel er
      where er.sharepoint_id = a.sharepoint_id
        and er.commentaire_attendu = c.texte)
returning c.id, a.sharepoint_id, c.texte;


-- ---------------------------------------------------------------------------
-- 3. Neuf anomalies où « déclarée » tombe APRÈS « faite » (ou « faite »
--    après « vérifiée ») dans l'export lui-même — impossible dans la vraie
--    vie. Pour chacune, échanger le jour et le mois d'UNE des deux dates
--    redonne un ordre cohérent (règle 16sexies : dates en texte, deux
--    formats mélangés). Cinq d'entre elles (461, 537, 638, 752, 777)
--    partagent le même « 06/02/2025 » — un seul jour de saisie touché sur
--    plusieurs lignes à la fois. Une inversion possible n'est pas une
--    certitude : à relire une par une avant de corriger depuis la fiche de
--    l'anomalie (elle-même, ou son passage) plutôt que par une écriture
--    directe ici.
-- ---------------------------------------------------------------------------
select sharepoint_id, champ, "valeur en base (probablement fausse)", "valeur si on inverse jour/mois"
  from (values

    (386, 'declare_le (Date)', date '2025-12-11', date '2025-11-12'),
    (380, 'declare_le (Date)', date '2025-12-10', date '2025-10-12'),
    (863, 'declare_le (Date)', date '2025-06-01', date '2025-01-06'),
    (461, 'date_intervention (FAIT_LE)', date '2025-02-06', date '2025-06-02'),
    (537, 'date_intervention (FAIT_LE)', date '2025-02-06', date '2025-06-02'),
    (638, 'date_intervention (FAIT_LE)', date '2025-02-06', date '2025-06-02'),
    (752, 'date_intervention (FAIT_LE)', date '2025-02-06', date '2025-06-02'),
    (777, 'date_intervention (FAIT_LE)', date '2025-02-06', date '2025-06-02'),
    (695, 'declare_le (Date)', date '2024-12-09', date '2024-09-12')

  ) as t(sharepoint_id, champ, "valeur en base (probablement fausse)", "valeur si on inverse jour/mois")
 order by sharepoint_id;

